---

- name: setup matrix
  hosts: matrix.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: borg_client, tags: ["borg"] }
    - { role: certbot }
    - { role: nginx }
    - role: postgres
      postgres_shared_buffers: 1GB
      postgres_work_mem: 32MB
      postgres_maintenance_work_mem: 32MB
      postgres_effective_cache_size: 2GB
      postgres_jit: 'off'
    - role: postfix
      postfix_relayhost: "mail.archlinux.org"
    - { role: matrix }
    - { role: fail2ban }
    - { role: prometheus_exporters }
