---
# TODO: make the playbook like archive-mirrors.yml
- name: setup repro2.pkgbuild.com
  hosts: repro2.pkgbuild.com
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: rebuilderd_worker }
    - { role: prometheus_exporters }
    - { role: fail2ban }
